FROM caddy AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY FileHub.sln ./
COPY ["FileHub.Common/*.csproj", "FileHub.Common/"]
COPY ["FileHub.Frontend/*.csproj", "FileHub.Frontend/"]
RUN dotnet restore "FileHub.Frontend/FileHub.Frontend.csproj"
COPY . .
WORKDIR "/src/FileHub.Frontend"
RUN dotnet build "FileHub.Frontend.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "FileHub.Frontend.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
